#{{ if not .Values.disableKube2MsbKube2MsbRegistrator }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube2msb-registrator
  namespace: "{{ .Values.nsPrefix }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube2msb-registrator
  template:
    metadata:
      labels:
        app: kube2msb-registrator
      name: kube2msb-registrator
    spec:
      hostname: kube2msb-registrator
      initContainers:
      - command:
        - /root/ready.py
        args:
        - --container-name
        - msb-discovery
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: {{ .Values.image.readiness }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: kube2msb-registrator-readiness
      containers:
      - args:
        image: {{ .Values.image.kube2msb }}
        name: kube2msb-registrator
        env:
        - name: KUBE_MASTER_URL
          value: {{ .Values.kubeMasterUrl }}
        - name: AUTH_TOKEN
          value: {{ .Values.kubeMasterAuthToken }}
        - name: MSB_URL
          value: {{tpl $.Values.discoveryUrl .}}
        imagePullPolicy: {{ .Values.pullPolicy }}
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}
